---

- name: "Ensure urlwatch and dependencies are present & latest"
  pip:
    state: latest
    name:
      - pyyaml 
      - minidb
      - requests
      - keyring
      - appdirs
      - lxml
      - cssselect
      - urlwatch
