---

- name: "Ensure pip is installed"
  apt:
    state: latest
    name: 
      - python3-pip
      - python-setuptools

- name: "Ensure urlwatch and dependencies are present & latest"
  pip:
    state: latest
    executable: pip3
    virtualenv_python: python3.6
    name:
      - pyyaml 
      - minidb
      - requests
      - keyring
      - appdirs
      - lxml
      - cssselect
      - urlwatch
      - keyrings.alt

- name: Ensure Postgres environment variables file created
  template:
    src: "{{ item }}.j2"
    dest: "{{ urlwatch_config_path }}/{{ item }}"
    mode: 0640
  with_items:
    - urls.yaml
    - urlwatch.yaml

- name: Ensure a a cronjob exists. Creates an entry like "0 5 * * /usr/local/bin/urlwatch"
  cron:
    name: "urlwatch"
    minute: "0"
    hour: "5"
    job: "/usr/local/bin/urlwatch"