---

- name: "Ensure pip is installed"
  apt:
    state: latest
    name: 
      - python3-pip
      - python-setuptools
      - expect

- name: "Ensure urlwatch and dependencies are present & latest"
  pip:
    state: latest
    executable: pip3
    virtualenv_python: python3.6
    name:
      - pyyaml 
      - minidb
      - requests
      - keyring
      - appdirs
      - lxml
      - cssselect
      - urlwatch
      - keyrings.alt

- name: "Ensure urlwatch is configured"
  template:
    src: "{{ item }}.j2"
    dest: "{{ urlwatch_config_path }}/{{ item }}"
  with_items:
    - urls.yaml
    - urlwatch.yaml

- name: "Ensure python keyring is configured"
  template:
    src: "keyringrc.cfg.j2"
    dest: "/root/.local/share/python_keyring/keyringrc.cfg"

- name: Set/update smtp password into keyring # /root/.local/share/python_keyring/crypted_pass.cfg
  expect:
    echo: yes
    command: "/usr/local/bin/urlwatch --smtp-login"
    timeout: 5
    responses:
      (.*)Enter password for(.*): "{{ urlwatch_smtp_pass }}"
      (.*)already set(.*) update(.*): "y"
  when: urlwatch_smtp_pass != ""

- name: Ensure a a cronjob exists. Creates an entry like "0 5 * * /usr/local/bin/urlwatch"
  cron:
    name: "urlwatch"
    minute: "{{ urlwatch_cron_minute }}"
    hour: "{{ urlwatch_cron_hour }}"
    job: "/usr/local/bin/urlwatch"